version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/LMS-BE

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/run_migrations.sh   # <---- added
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user