version: 0.2

env:
  variables:
    DB_HOST: "DB_HOST"   # Your DB EC2 public IP
    DB_USER: "DB_PASS"
    DB_PASS: "DB_PASS"
    DB_NAME: "DB_NAME"
    JWT_SECRET: "JWT_SECRET"

phases:
  install:
    runtime-versions:
      nodejs: 18  
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Preparing deployment bundle"


artifacts:
  files:
    - dist/**/*
    - scripts/**/*
    - package.json
    - appspec.yml